version: '3.7'
services:
#  web:
#    build: .
#    ports:
#      - "5000:5000"
#    volumes:
#      - .:/code 
#      # 把當前資料夾 mount 掛載進去 container，這樣你可以直接在本地端專案資料夾改動檔案，container 裡面的檔案也會更動也不用重新 build image！
#    stdin_open: true  # -i interactive
#    tty: true # -t tty

  prometheus:
    image: prom/prometheus:v2.17.0
    #container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./prometheus/data:/prometheus/data
      - /etc/localtime:/etc/localtime
    hostname: prometheus
    #restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - '9090:9090'
    networks:
      - network_nginx
    user: '0:0'

  grafana:
    image: grafana/grafana:6.7.1-ubuntu # for arm64
    #container_name: grafana
    volumes: 
      - /etc/localtime:/etc/localtime
      - ./grafana/var/lib/grafana:/var/lib/grafana
      - ./grafana/etc/grafana:/etc/grafana
    hostname: grafana
    #restart: always
    ports:
      - "3000:3000"
    networks:
      - network_nginx

  node-exporter:
    image: quay.io/prometheus/node-exporter
    #container_name: node-exporter
    volumes:
      - /etc/localtime:/etc/localtime
    hostname: node-exporter
    #restart: always
    ports:
      - "9100:9100"
    networks:
      - network_nginx

#  cadvisor:
#    image: google/cadvisor:latest
#    container_name: cadvisor
#    hostname: cadvisor
#    restart: always
#    privileged: true
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:rw
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
#      - /cgroup:/cgroup:ro
#    ports:
#      - "8080:8080"
networks:
  network_nginx:
    name: network_nginx
    external: true 


x-settings:
  deploy:
    stack_name: monitor
    enable: true
    priority: "200"
